version: 2
updates:
  # Backend Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
    assignees:
      - "your-github-username"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "frontend"
    assignees:
      - "your-github-username"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Ignore major version updates for React
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  # Root npm dependencies (E2E tests)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "testing"
    assignees:
      - "your-github-username"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "ci/cd"
    assignees:
      - "your-github-username"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
      - "docker"
    assignees:
      - "your-github-username"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "dependencies"
      - "docker"
    assignees:
      - "your-github-username"